import { hexToRgb } from '../utils';

const Colors = {
  TRANSPARENT: 'transparent',
  PRIMARY_COLOR: '#0E2C39',
  ACCENT_COLOR: '#39CFBA',
  ACCENT_REVERSE: '#FCE9AD',
  WHITE_COLOR: '#FFFFFF',
  BLACK_COLOR: '#000000',
  SHADOW_COLOR: hexToRgb('#000000', 0.29),
  Fancy: {
    COLOR_GREEN: '#159782',
    COLOR_YELLOW: '#FBC02E',
    COLOR_RED: '#BA0000',
    COLOR_PURPLE: '#AD00AD',
    COLOR_ORANGE: '#FD9976',
  },
  Button: {
    PRIMARY_COLOR: '#39CFBA',
    YELLOW_COLOR: '#FBC02E',
  },
  Icon: {
    PRIMARY_COLOR: '#001F5F',
  },
  TextInput: {
    TINT_COLOR_GREEN: '#B9F8EC',
  },
  Shades: {
    COLOR_GREEN: '#B9F8EC',
    COLOR_BLUE: '#E0FAFF',
    COLOR_INACTIVE: '#C1C1C1',
    COLOR_PLACEHOLDER: '#707070',
    COLOR_BLACK: '#000000',
    COLOR_MINE_SHAFT: '#333333',
    COLOR_DOVE_GRAY: '#666666',
    COLOR_DUSTY_GRAY: '#999999',
    COLOR_SILVER: '#CCCCCC',
    COLOR_MERCURY: '#E6E6E6',
    COLOR_CONCRETE: '#F3F3F3',
    COLOR_ERROR: '#B00020',
    COLOR_VERY_LIGHT_GREY: '#F2F4F5',
  },
  Background: {
    SCREEN_COLOR: '#FFFFFF',
    GREEN_COLOR: '#EBFFFB',
    YELLOW_COLOR: '#FEF9E9',
  },
};
export { Colors };
